### ISSUE TITLE
Android app not logging into Mitro account

### ISSUE THREAD

**Issue by levibostian** [mitro-co/mitro#115]
I have used Mitro for a few months now and a couple days ago I converted completely over to using Mitro as my primary password manager. 

This morning I got Intellij IDEA 14 to open up the Android project and install it to my Android device via USB. 

When I go to login, I enter my credentials and it says "Incorrect login info or bad network connection". I know my Internet is working fine as every other app works and my credentials are correct because on Chrome I just signed out and signed back in with those credentials. 

I just now noticed that the Android app got taken down from the Android store. Does this have anything to do with not being able to login? Should I try to figure out a way to run my own Mitro server (not preferred) or should I go to another password manager (not preferred)?

**Comment by rackergs** [comment]
I'm having this issue as well. Some response would be handy as this tool has quickly become indispensable our office.

**Comment by levibostian** [comment]
Forgot this issue is still open. Well, Mitro is shut down which explains why it didn't work. Bye bye.
