### ISSUE TITLE
ant test / runtest.sh do not pass

### ISSUE THREAD

**Issue by roeler** [mitro-co/mitro#79]
Hello,

I want to make the password manager in an local environment for my local network based on Ubuntu (12.04 atm). I followed all of the instructions with success (thanks in advance for this howto: https://www.hashtagsecurity.com/mitro-login-manager-on-premise-2/) . I setup the postgresql database with success. I have run the mitro-server with the 'ant server' command with success. I do get data when I browse to the http://localhost:8443/mitro-core/api/BuildMetadata. I successfully compiled the browser extension for Firefox (the debug version and the normal version) and install it to the browser, but when I browse to http://localhost:8443 I got an 404 error message instead of the possibility to create a new account.

When I try to run the "mitro-core/ant test" or the "browser-ext/api/js/cli/runtest.sh FAST" commands I got the following error:

BUILD FAILED:
/srv/mitro/mitro-core/build.xml: 164: The following error occured while executing this line:
/srv/mitro/mitro-core/build.xml: 95: Test failed

It is the only error I get at this point and I guess this must be the reason why I still got an 404-error when I browse the localhost:8443 and can not create a new user. Any suggestions about what I am doing wrong? After two evenings and nights working on it I am stuck on this.

**Comment by winstonhong** [comment]
Hello roeler.

Any progress on mitro server installation on ubuntu 12.04?

I face with the exactly issue as you.

If you show more details, you can find that the issue is caused by MitroServletTest.java
that is, Testsuite: co.mitro.core.servlets.MitroServletTest

    [junit] Testcase: testDeprecatedUserId took 0.963 sec
    [junit] Testcase: testNewStylePrivateUserGroup took 0.15 sec
    [junit] Testcase: testOldStylePrivateUserGroup took 0.103 sec
    [junit] Testcase: testSingleSecretAutoDeleteGroup took 0.115 sec
    [junit] Running co.mitro.core.servlets.MitroServletTest
    [junit] Testsuite: co.mitro.core.servlets.MitroServletTest
    [junit] Tests run: 8, Failures: 1, Errors: 1, Time elapsed: 17.163 sec
    [junit] Tests run: 8, Failures: 1, Errors: 1, Time elapsed: 17.163 sec
    [junit] ------------- Standard Output ---------------
    [junit] 
    [junit] WARNING: enabling "trust" authentication for local connections
    [junit] You can change this by editing pg_hba.conf or using the -A option the
    [junit] next time you run initdb.
    [junit] /tmp/junit2842599604428475656
    [junit] ------------- ---------------- ---------------
    [junit] 
    [junit] Testcase: testIdentityByName took 0.448 sec
    [junit] Testcase: testSignatures took 1.313 sec
    [junit] 	Caused an ERROR
    [junit] test timed out after 1000 milliseconds
    [junit] java.lang.Exception: test timed out after 1000 milliseconds
    [junit] 	at java.net.SocketInputStream.socketRead0(Native Method)
    [junit] 	at java.net.SocketInputStream.read(SocketInputStream.java:152)
    [junit] 	at java.net.SocketInputStream.read(SocketInputStream.java:122)
    [junit] 	at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:143)
    [junit] 	at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:112)
    [junit] 	at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:71)
    [junit] 	at org.postgresql.core.PGStream.ReceiveChar(PGStream.java:269)
    [junit] 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1700)
    [junit] 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
    [junit] 	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
    [junit] 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:417)
    [junit] 	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:302)
    [junit] 	at com.j256.ormlite.jdbc.JdbcCompiledStatement.runQuery(JdbcCompiledStatement.java:55)
    [junit] 	at com.j256.ormlite.stmt.SelectIterator.<init>(SelectIterator.java:55)
    [junit] 	at com.j256.ormlite.stmt.StatementExecutor.buildIterator(StatementExecutor.java:232)
    [junit] 	at com.j256.ormlite.stmt.StatementExecutor.query(StatementExecutor.java:181)
    [junit] 	at com.j256.ormlite.dao.BaseDaoImpl.query(BaseDaoImpl.java:263)
    [junit] 	at com.j256.ormlite.stmt.QueryBuilder.query(QueryBuilder.java:319)
    [junit] 	at co.mitro.core.server.data.DBIdentity.getUsersFromNames(DBIdentity.java:78)
    [junit] 	at co.mitro.core.server.data.DBIdentity.getIdentityForUserName(DBIdentity.java:529)
    [junit] 	at co.mitro.core.servlets.MitroServlet.doPost(MitroServlet.java:352)
    [junit] 	at co.mitro.core.servlets.MitroServletTest.makeRequest(MitroServletTest.java:233)
    [junit] 	at co.mitro.core.servlets.MitroServletTest.testSignatures(MitroServletTest.java:379)
    [junit] 
    [junit] Testcase: testTransactions took 0.983 sec
    [junit] Testcase: testImplicitTransactionError took 0.543 sec
    [junit] Testcase: testImplicitTransactions took 1.493 sec
    [junit] Testcase: readOnlyManagers took 0.285 sec
    [junit] Testcase: testCookieDecoder took 0.239 sec
    [junit] Testcase: testResponseEncoding took 0.365 sec
    [junit] Testcase: co.mitro.core.servlets.MitroServletTest took 0 sec
    [junit] 	FAILED
    [junit] null
    [junit] junit.framework.AssertionFailedError
    [junit] 	at co.mitro.core.servlets.MitroServletTest.tearDownSuite(MitroServletTest.java:178)
    [junit] 

BUILD FAILED
/home/mitro/mitro/mitro-core/build.xml:164: The following error occurred while executing this line:
/home/mitro/mitro/mitro-core/build.xml:95: Tests failed

I do not how many test suits will run by "ant test". Testsuite: co.mitro.core.servlets.MitroServletTest is the test suite 39. As this test suite got the issue, the test procedure is automatically terminated.

**Comment by roeler** [comment]
Nope, on Ubuntu 12.04 it didn't work. Now busy with Ubuntu 14.04 and that looks a little bit better. But now I have problems with the browser extension in Chrome (or any other), the mitroSignup function doesn't work, so it isn't possible to register a new user. Still getting the same errors :) As soon as it works I will write a blog with a howto for Ubuntu 14

**Comment by winstonhong** [comment]
Hello roeler.

Thank you very much for your quick response.

I comment out the line 178 of  MitroServletTest.java

//assert code == 0;

https://github.com/mitro-co/mitro/blob/master/mitro-core/java/server/test/co/mitro/core/servlets/MitroServletTest.java

run "ant test" on ubuntu 12.04, get "BUILD SUCCESSFUL".

    [junit] Testcase: testDoPostWithBackup took 0.218 sec
    [junit] Testcase: testDoPostWrongCode took 0.316 sec
    [junit] Testcase: testDoPostWithCode took 2.217 sec
    [junit] Testcase: testEmailHarvesting took 0.139 sec

BUILD SUCCESSFUL
Total time: 1 minute 27 seconds

After running "ant server", I access https://localhost:8443/mitro-core/api/BuildMetadata

the server is running

commit: 8c374fadf8f40879ce1abcfcf15109dc61e28811
describe: fatal: No names found, cannot describe anything.
build time: 2015-01-16T22:21:58Z

However, 

when I access https://localhost:8443/mitro-core/

the webpage of mitro login does NOT show up, as shown in the following link

resource://mitro-login-manager-at-jetpack/mitro-login-manager/data/html/popup.html

Instead, I get the error message

HTTP ERROR: 404

Problem accessing /mitro-core/. Reason:

    Not Found
Powered by Jetty://

**Comment by roeler** [comment]
The website part isn't really working when you try to host it yourself (too bad, I am hoping for a quick guide how to fix this for a local setup!). I was trying the same thing as you, but that doesn't work. As soon as your server is running with ant server you should start building an extension for chrome or Firefox. 

Go to browser-ext and run the ./build.sh script. After the script is done you see a comment that you should export a variable NODE_PATH (I believe, I am not sure about that). Don't forget that, because I am not sure if thay would make a difference. Now you can go to browser-ext/login en start building the extension. But not before you check and edit the common/config for config.debug in browser-ext/login/common/config/config.debug.js and change the setting for your localhost (You could do the same for release).

Now go to browser-ext/login and run "make firefox-debug" to build a debug.xpi file in build/firefox/debug/debug.xpi. Start firefox and import the extension by hand. In the upper right corner you should see the Mitro icon. Click it and select sign up. The extension window should open to start a new user registration.

If you don't have the emailer to start working (If you do, please tell me your magic!) you can go to mitro-core/tools/ and run verifydevice.py to get the url to verify the account. Make sure you have created a local account by login in into the postgresql database and query the tables to find your account. That just did the tric for me and now I have a working firefox extension. But I am still struggling with the webpage extension (some weird javascript errors) and that is what I wanted to use.

**Comment by winstonhong** [comment]
Hello roeler.

Thank you very much for your great guidance.

I follow your guidance as follows.

(1) 
$pg_ctl -D /home/inbay/mitro/mitro-core/build/postgres -l logfile start
$cd mitro/mitro-core
$ant server

(2) $cd mitro/browser-ext/api
$./build.sh

To run JS stuff:
export NODE_PATH=/home/mitro/mitro/browser-ext/api/build/node/lib/node_modules

$export NODE_PATH=/home/mitro/mitro/browser-ext/api/build/node/lib/node_modules

(3) $sudo vi browser-ext/login/common/config/config.debug.js

var debugMode = true;
var MITRO_HOST = 'localhost';
var MITRO_PORT = 8443;
var MITRO_AGENT_HOST = 'localhost';
var MITRO_AGENT_PORT = 8444;
var FAILOVER_MITRO_HOST = null;
var FAILOVER_MITRO_PORT = null;
var FIREFOX;
var CHROME;
var SAFARI;
var WEBPAGE;

I do NOT make any changes on config.debug.js.

$sudo vi browser-ext/login/common/config/config.release.js 
var debugMode = false;
var MITRO_HOST = 'www.mitro.co';
var MITRO_PORT = 443;
var MITRO_AGENT_HOST = 'mitroaccess.com';
var MITRO_AGENT_PORT = 443;
var FAILOVER_MITRO_HOST = 'secondary.mitro.ca';
var FAILOVER_MITRO_PORT = 443;
var FIREFOX;
var CHROME;
var SAFARI;
var WEBPAGE;

I do NOT make any changes on config.release.js.

Would you please give me some guidance on how to modify the above two files?

(4) $cd mitro/browser-ext/login

$make firefox-debug

The following messages are displayed in the screen.
***********************************************************************
kzjs_srouces = ../api/build/node/lib/node_modules/keyczarjs/*.js
forge_srouces = ../api/build/node/lib/node_modules/keyczarjs/node_modules/node-forge/js/*.js
cp firefox/button.html /home/mitro/mitro/browser-ext/login/build/firefox/debug/data/
# getting the script tags commented
cp /home/mitro/mitro/browser-ext/login/build/firefox/debug/data/js/client.js /home/mitro/mitro/browser-ext/login/build/firefox/debug/lib
cp /home/mitro/mitro/browser-ext/login/build/firefox/debug/data/utils.js /home/mitro/mitro/browser-ext/login/build/firefox/debug/lib
cp /home/mitro/mitro/browser-ext/login/build/firefox/debug/data/helpers_common.js /home/mitro/mitro/browser-ext/login/build/firefox/debug/lib
./extract_scripts.py collect /home/mitro/mitro/browser-ext/login/build/firefox/debug/data
# building xpi
cd /home/mitro/mitro/browser-ext/login/build/firefox && \
	/home/mitro/mitro/browser-ext/login/build/../../third_party/firefox-addon-sdk/bin/cfx xpi --pkgdir=debug && \
	mv mitro-login-manager.xpi debug.xpi
Exporting extension to mitro-login-manager.xpi.
*****************************************************************************

(5) Start firefox at ubuntu 12.04
I access

https://localhost:8443/mitro-core/api/BuildMetadata

commit: 8c374fadf8f40879ce1abcfcf15109dc61e28811
describe: fatal: No names found, cannot describe anything.
build time: 2015-01-17T02:51:24Z

Then I access

https://localhost:8443/

HTTP ERROR: 404

Problem accessing /. Reason:

    Not Found

Powered by Jetty://

I do NOT how to import the extension by hand

Then I access

https://localhost:8443/mitro-core/

HTTP ERROR: 404

Problem accessing /mitro-core/. Reason:

    Not Found

Powered by Jetty://

(6) I also try the perform the procedures (2) to (5) before the procedure (1).

However, I still do NOT how to import the extension by hand for Firefox.

**Comment by roeler** [comment]
I suggest you use Google to check how you can install an add-on by hand :) I no longer have issues with the ant run tests since I use Ubuntu 14.04. So I close this issue. :)
